Flask-Web-App-Tutorial/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

class Feedback(db.Model):
    __tablename__ = 'feedback'
    id = db.Column(db.Integer, primary_key=True)
    nama_lahan = db.Column(db.String(200), unique=True)
    tanaman = db.Column(db.String(200))
    luas = db.Column(db.Integer)
    deskripsi = db.Column(db.Text())

Flask-Web-App-Tutorial/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "postgresql://jonathan:123456@188.166.239.153/msmb"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://jonathan:123456@188.166.239.153/msmb'

    db.init_app(app)

    from .views import views
    from .lahan import lahan
    from .auth import auth
    from .deteksi import deteksi

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(lahan, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(deteksi, url_prefix='/')

    from .models import User, Note, Feedback

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

Flask-Web-App-Tutorial/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

Flask-Web-App-Tutorial/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, request, redirect, current_app, send_from_directory
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from werkzeug.exceptions import RequestEntityTooLarge
import os
from .models import Note
from . import db
import json

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST': 
        note = request.form.get('note')#Gets the note from the HTML 

        if len(note) < 1:
            flash('Note is too short!', category='error') 
        else:
            new_note = Note(data=note, user_id=current_user.id)  #providing the schema for the note 
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)

@views.route('/images')
def image():
    current_app.config['UPLOAD_DIRECTORY'] = 'uploads/'
    current_app.config['ALLOWED_EXTENSIONS'] = ['.jpg', '.jpeg', '.png', '.gif']
    files = os.listdir(current_app.config['UPLOAD_DIRECTORY'])
    images = []
    for file in files:
        extension = os.path.splitext(file)[1].lower()
        if extension in current_app.config['ALLOWED_EXTENSIONS']:
            images.append(file)

    return render_template("image.html", images=images, user=current_user)

@views.route('/upload', methods=['GET', 'POST'])
def upload():
    current_app.config['UPLOAD_DIRECTORY'] = 'uploads/'
    current_app.config['MAX_CONTENT_LENGTH'] = 16*1024*1024
    current_app.config['ALLOWED_EXTENSIONS'] = ['.jpg', '.jpeg', '.png', '.gif']
    try:
        file = request.files['file']
        extension = os.path.splitext(file.filename)[1]
        if file:
            if extension not in current_app.config['ALLOWED_EXTENSIONS']:
                flash('File is not an image')
                return redirect('/images')
            file.save(os.path.join(current_app.config['UPLOAD_DIRECTORY'], secure_filename(file.filename)))

    except RequestEntityTooLarge:
        flash('File is larger than the 16MB limit')
        return redirect('/images')
    return redirect('/images')

@views.route('/uploads/<filename>', methods=['GET'])
def uploads(filename):
    current_app.config['ALLOWED_EXTENSIONS']
    current_app.config['UPLOAD_DIRECTORY'] = 'uploads/'
    return send_from_directory(current_app.config['UPLOAD_DIRECTORY'], filename)

@views.route('/delete-note', methods=['POST'])
def delete_note():  
    note = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

Flask-Web-App-Tutorial/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="shortcut icon" href="{{ url_for('static', filename="ritx_sf_fav.png") }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename="ritx_sf_fav.png") }}" type="image/x-icon">

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #ff8360;">
      <button style="background-color: #e8e288;"
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbar" >
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <img src="{{ url_for('static', filename="msmb.png") }}" alt="logo"width="100" class="mr-5">
          <a class="nav-item nav-link" id="home" href="/"  style="color: black;">Home</a>
          <a class="nav-item nav-link" id="home" href="/images"  style="color: black;">Image</a>
          <a class="nav-item nav-link" id="home" href="/deteksi"  style="color: black;">Deteksi Hama</a>
          <a class="nav-item nav-link" id="home" href="/lahan"  style="color: black;">Lahan</a>
          <a class="nav-item nav-link" id="logout" href="/logout"  style="color: black;">Logout</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

Flask-Web-App-Tutorial/website/templates/chat.html
{% extends 'base.html' %} {% block content %}
<form method="post" class="buttons">
  <h3>Enter The Chat Room</h3>
  <div>
    <label>Name:</label>
    <input
      type="text"
      placeholder="Pick a name!"
      name="name"
      value="{{name}}"
    />
  </div>
  <div class="join">
    <input type="text" placeholder="Room Code" name="code" value="{{code}}" />
    <button type="submit" name="join">Join a Room</button>
  </div>
  <button type="submit" name="create" class="create-btn">Create a Room</button>
  {% if error %}
  <ul>
    <li>{{error}}</li>
  </ul>
  {% endif %}
</form>
{% endblock %}

Flask-Web-App-Tutorial/website/templates/deteksi.html
{% extends "base.html" %}
{% block title %}Deteksi Hama{% endblock %}

{% block content %}
<body>
    <h1>Silahkan Unggah Gambar</h1>
    <div class="app">
        <div class="form-section">
            <form method="POST" enctype="multipart/form-data" style="align-content: center; text-align: center;display: flex;">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    <input type="file" name="file" class="form-control" autocomplete="off" required>
                </div>
                <div class="form-group">
                    <button type="submit" name="favorite" value="x" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>

        <section class="col-sm">
            <img src="{{ url_for('deteksi.video') }}" alt="Upload video" style="max-width: 100%; max-height: 300px;">
        </section>
    </div>
</body>
{% endblock %}

Flask-Web-App-Tutorial/website/templates/home.html
<html>
{% extends "base.html" %}
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
{% block content %}
<body>
  <h1 align="center">Notes</h1>
  <ul class="list-group list-group-flush" id="notes">
    {% for note in user.notes %}
    <li class="list-group-item">
      {{ note.data }}
      <button type="button" class="close" onClick="deleteNote({{ note.id }})">
        <span aria-hidden="true">&times;</span>
      </button>
    </li>
    {% endfor %}
  </ul>
  <form method="POST">
    <textarea name="note" id="note" class="form-control"></textarea>
    <br />
    <div align="center">
      <button type="submit" class="btn btn-primary">Add Note</button>
    </div>
  </form>
</body>
{% endblock %}
</html>

Flask-Web-App-Tutorial/website/templates/image.html
{% extends "base.html" %} 
{% block title %}Image{% endblock %}  
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>File Uploads</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
{% block content %}
<body>
  <h1>Silahkan Unggah Gambar</h1>
  <div class="app">
    <div class="form-section">
      <form method="post" action="/upload" enctype="multipart/form-data">
        <dl>
          <p>
              <input type="file" name="file" class="form-control" autocomplete="off" required>
          </p>
        </dl>
        <p>
          <input type="submit" value="Upload" class="btn btn-info">
        </p>
      </form>
    </div>

    <div class="images-section">
      {% for image in images %}
        <a href="{{ url_for('views.uploads', filename=image) }}">
          <img src="{{ url_for('views.uploads', filename=image) }}" alt="image" style="width: 400px;"/>
        </a>
      {% endfor %}
    </div>
    
  </div>
</body>
{% endblock %}

</html>


Flask-Web-App-Tutorial/website/templates/indexproject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ObjectDetection-YOLOv8</title>
    <style>
        body{
        font-family:Helvetica, sans-serif;
        margin:0px;
        padding:0px;
        }
        header.feature-box.right{
        background-color:black;
        color:white;
        height:120px;
        padding:5px;
        text-align:right;
        }
        header.feature-box.below{
        height:800px;
        background-color:blue;
        margin-top:-30px;
        background-image:url("../static/images/1.png");
        background-size:100%;
        background-position:center;
        }
        ul{
        list-style:none;
        padding:0px;}
        li{
        display:inline-block;
        background-color:gray;
        border-radius:10px;
        padding:10px;
        margin:10px;
        }
        li:hover{
        background-color:red;
        margin:10px;
        }
        header a{
        color:white;
        text-decoration:none;
        width:100%;
        }
        .details{
        height:80px;
        margin:40px;
        padding:0px;
        font-size:40px;
        background-color:gray;
        text-align:center;
        color:black;
        }


        .features{
        background:white;
        color:gray;
        display:flex;
        flex-direction:row;
        padding:20px;

        }
        .features figure
        {/*background:pink;*/
        width:400px;
        margin:auto;
        text-align:center;
        text-transform:uppercase;
        }
        .features figure img{
        border-radius:10%;
        width:400px;
        }
        div.main{
        display:flex;
        margin:40px;
        letter-spacing:1px;
        h1, h2, h3, h4, h5, h6 {
          font-family: "Playfair Display";
    letter-spacing: 5px;
        }
        }
        .subpart2{
        text-align:center;
        text-transform:uppercase;
        }
        .subpart2 figure img{
        border-radius:4%;
        width:800px;
        }
        .contactpage{
        margin:20px;
        }
        #textbox {
       font-size: 18pt;
        height: 42px;
        width : 1000px;
        }
        #textboxes {
       font-size: 18pt;
        height: 42px;
        width : 1000px;
        }
        footer{
        background-color:black;
        text-align:center;
        margin:0px;
        padding:0px;
        color:white;
        font-size:20px;
        }

    </style>
</head>
<body>
    <header class="feature-box right">
        <nav>
            <ul>
            <li><a href="/home">Home</a></li>
            <li><a href="/FrontPage">Video</a></li>
            <li><a href="/webcam">LiveWebcam</a></li>
            </ul>
        </nav>
    </header>

    <header class="feature-box below">
    </header>


    <section class="details">
        <h1>Sample Results</h1>

    </section>
    <section class="features">
        <figure>
            <img src="../static/images/1.png" alt="YOLOv8 Results 1">
            <figcaption>YOLOv8 Results 1</figcaption>
        </figure>
        <figure>
            <img src="../static/images/2.png" alt="YOLOv8 Results 2">
            <figcaption>YOLOv8 Results 2</figcaption>
        </figure>
        <figure>
            <img src="../static/images/3.png" alt="YOLOv8 Results 3">
            <figcaption>YOLOv8 Results 3</figcaption>
    </figure>
    </section>
    <div class="main">
        <div class="subpart1">
            <h1>Object Detection using YOLOv8</h1><br>
            <h4> FPS of Video</h4>
            <p>FPS represents the Frame Rate, in case of GPU the FPS will be high while in case of CPU the FPS will be low</p><br>
            <h4>Shape of Current Frame</h4>
            <p>The shape of current frame i.e. Resolution will be calculated</p><br>
            <h4>Detections in Current Frame</h4>
            <p>Total detections in each of the frame will be calculated</p><br>

        </div>

      <div class="subpart2"><figure>
      <img src="../static/images/1.png"  alt="Image Missing">
          <figcaption>Sample Results</figcaption>
        </figure>
      </div>
  </div>

<div class="contactpage">
    <h1>Contact</h1><br>
    <p>In case of any query do let me know</p>
        <form action="/action_page.php" target="_blank" >
            <p><input type="text" placeholder="Name"  required name="Name"  id="textbox"></p>
            <p><input type="text" placeholder="Email ID" required name="Email ID" id="textboxes"></p>
            <p><button type="submit">SEND MESSAGE</button></p>
        </form>
</div>

<footer>
    <p>YOLOv8 Lecture Series <a href="https://www.youtube.com/channel/UC--6PuiEdiQY8nasgNluSOA" title="YouTube Channel"> YouTube Channel</a></p>
</footer>
</body>
</html>

Flask-Web-App-Tutorial/website/templates/lahan.html
{% extends "base.html" %} 
{% block title %}Nama Lahan{% endblock %}  

{% block content %}
  <body>
    <img src="{{ url_for('static', filename="msmb.png") }}" style="width: 25%; margin-left: 38%;" />
    <div class="container" style="margin: 30px; border-radius: 20px; background-color:  #7dce82; padding-top: 5%; padding-bottom: 3%;">
      <form action="/submit" method="POST">
        <div class="form-group">
          <h3>Nama Lahan</h3>
          <input
            type="text"
            name="nama_lahan"
            placeholder="Nama Lahan"
          />
        </div>
        <div class="form-group">
          <h3>Tanaman</h3>
          <select name="tanaman">
            <option value="">Pilih Jenis Tanaman</option>
            <option value="Cabe">Cabe</option>
            <option value="Jagung">Jagung</option>
            <option value="Padi">Padi</option>
            <option value="Semangka">Semangka</option>
          </select>
        </div>
        <div class="form-group">
          <h3>Berapa Luas Tanah Anda</h3>
          <input
            type="text"
            name="luas"
            placeholder="Luas Lahan"
          />
        </div>
        <div class="form-group">
          <h3>Deskripsi Lahan</h3>
          <textarea
            name="deskripsi"
            id=""
            cols="30"
            rows="10"
            placeholder="Deskripsikan Kondisi Lahan Anda"
          ></textarea>
        </div>
        <input type="submit" value="Submit" class="btn btn-primary" style="background-color: #ff8360;"/>
      </form>
    </div>
  </body>
{% endblock %}

Flask-Web-App-Tutorial/website/templates/login.html
{% extends "base.html" %} 
{% block title %}Login{% endblock %} 
{% block content %}
<style>
    .fade-in {
        opacity: 0; /* Mulai dari keadaan tidak terlihat */
        animation: fadeInAnimation 1s ease forwards; /* Gunakan animasi fadeInAnimation */
    }

    @keyframes fadeInAnimation {
        from {
            opacity: 0; /* Mulai dengan keadaan tidak terlihat */
        }
        to {
            opacity: 1; /* Akhir dengan keadaan terlihat */
        }
    }
</style>
<h1 class="fade-in" style="margin: 30px; border-radius: 20px;">Sistem Informasi Lahan dan Tanaman</h1>
<div style="margin: 30px; border-radius: 20px; background-color: #7dce82; padding-top: 5%; padding-bottom: 3%;">
    <form method="POST">
        <img src="{{ url_for('static', filename="msmb.png") }}" style="width: 25%; margin-left: 38%;" />
        <h3 align="center" style="color: black;">Login</h3>
        <div class="form-group" style="width: 90%; margin-left: 5%; ">
            <label for="email" style="color: black;">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
        </div>
        <div class="form-group" style="width: 90%; margin-left: 5%;">
            <label for="password" style="color: black;">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
        </div>
        <br />
        <button type="submit" class="btn btn-primary" style="margin-bottom: 2%; margin-left: 5%; background-color: #ff8360;">Login</button>
        <p style="color: black; margin-left: 5%">Belum punya akun? <a style="color: #ff8360;" href="/sign-up">Sign Up</a></p>
    </form>
</div>

<script>
    const fadeInElements = document.querySelectorAll('.fade-in');
    const fadeInObserver = new IntersectionObserver((entries, observer) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.classList.add('visible');
                observer.unobserve(entry.target);
            }
        });
    });

    fadeInElements.forEach(element => {
        fadeInObserver.observe(element);
    });
</script>
{% endblock %}

Flask-Web-App-Tutorial/website/templates/room.html
{% extends 'base.html' %} {% block content %}
<div class="message-box">
  <h2>Chat Room: {{code}}</h2>
  <div class="messages" id="messages"></div>
  <div class="inputs">
    <input
      type="text"
      rows="3"
      placeholder="Message"
      name="message"
      id="message"
    />
    <button type="button" name="send" id="send-btn" onClick="sendMessage()">
      Send
    </button>
  </div>
</div>
<script type="text/javascript">
  var socketio = io();

  const messages = document.getElementById("messages");

  const createMessage = (name, msg) => {
    const content = `
    <div class="text">
        <span>
            <strong>${name}</strong>: ${msg}
        </span>
        <span class="muted">
            ${new Date().toLocaleString()}
        </span>
    </div>
    `;
    messages.innerHTML += content;
  };

  socketio.on("message", (data) => {
    createMessage(data.name, data.message);
  });

  const sendMessage = () => {
    const message = document.getElementById("message");
    if (message.value == "") return;
    socketio.emit("message", { data: message.value });
    message.value = "";
  };
</script>
{% for msg in messages %}
<script type="text/javascript">
  createMessage("{{msg.name}}", "{{msg.message}}");
</script>
{% endfor %} {% endblock %}

Flask-Web-App-Tutorial/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST" style="margin: 30px; border-radius: 20px; background-color:  #7dce82; padding-top: 5%; padding-bottom: 3%;">
  <img src="{{ url_for('static', filename="msmb.png") }}" style="width: 25%; margin-left: 38%;"/>
  <h3 align="center" style="">Sign Up</h3>
  <div class="form-group" style="width: 90%; margin-left: 5%;">
    <label for="email">Email Address</label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
  </div>
  <div class="form-group" style="width: 90%; margin-left: 5%;">
    <label for="firstName">First Name</label>
    <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name"/>
  </div>
  <div class="form-group" style="width: 90%; margin-left: 5%;">
    <label for="password1">Password</label>
    <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password"/>
  </div>
  <div class="form-group" style="width: 90%; margin-left: 5%;">
    <label for="password2">Password (Confirm)</label>
    <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password"/>
  </div>
  <br />
  <button type="submit" class="btn btn-primary" style="margin-bottom: 2%; margin-left: 5%; background-color: #ff8360;">Submit</button>
  <p  style="color: black; margin-left: 5%">Sudah punya akun? <a style="color: #ff8360;" href="/login">Login</a></p>
</form>
{% endblock %}

Flask-Web-App-Tutorial/website/templates/src/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Slide Navbar</title>
	<link rel="stylesheet" type="text/css" href="slide navbar style.css">
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form>
					<label for="chk" aria-hidden="true">Sign up</label>
					<input type="text" name="txt" placeholder="User name" required="">
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Sign up</button>
				</form>
			</div>

			<div class="login">
				<form>
					<label for="chk" aria-hidden="true">Login</label>
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Login</button>
				</form>
			</div>
	</div>
</body>
</html>

Flask-Web-App-Tutorial/website/templates/success.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="../static/style.css" />
    <title>Thank You!</title>
  </head>
  <body>
    <div class="container">
      <img src="../static/logo.png" alt="" class="logo" />
      <h1>Thank You!</h1>
      <h2>Thank you for rating your experience. We hope to see you soon!</h2>
    </div>
  </body>
</html>